Repository xbmc/inputstream.adaptive, pull requests merged in 2021-04, with the labels that each got.

#564 Fix MPD Timing (remove publishTime & presentationTimeOffset)
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/segtimeline_old_publish_time.mpd
  src/test/manifests/mpd/segtimeline_pto.mpd
Labels: bug fix, include tests

#626 [Dash] Correctly set timeshift_buffer (live)
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/segtimeline_live_pd.mpd
Labels: bug fix, include tests

#602 [Dash] Fix missing audio languages
  src/parser/DASHTree.cpp
Labels: bug fix

#618 [DASH] Support ec-3 channel count (urn:mpeg:mpegB:cicp:ChannelConfiguration)
  src/parser/DASHTree.cpp
Labels: feature

#575 [Dash] Support fpsScale in AdaptationSets
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/fps_scale_adaptset.mpd
Labels: bug fix, include tests

#635 fix debian/ubuntu packaging
  debian/control
Labels: bug fix

#601 Change decrypter search path for Android
  CMakeLists.txt
  Jenkinsfile
  README.md
  inputstream.adaptive/addon.xml.in
  src/main.cpp
Labels: require discussion

#625 Don't overwrite manifest headers with stream_headers & default stream_headers to manifest headers
  src/main.cpp
Labels: feature

#563 Seperate ac3 (DD) and eac3 (DD+)
  src/main.cpp
Labels: require discussion

#630 [Dash] Allow both $Time and $Number in URL
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/placeholders.mpd
Labels: bug fix, needs tests

#645 [Dash] Default update_parameter to full if using SegmentTimeline
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/segtimeline_vod.mpd
  src/test/manifests/mpd/segtpl_old_publish_time.mpd
  src/test/manifests/mpd/segtpl_pto.mpd
Labels: feature, needs tests

#621 [Dash] Remove reliance on namespace for pssh and default_kid
  src/helpers.cpp
  src/helpers.h
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/pssh_default_kid.mpd
Labels: include tests, require discussion
