Repository xbmc/inputstream.adaptive, pull requests merged in 2022-11, with the labels that each got.

#1062 Fix memory leak in AdaptiveTree::SortTree
  src/common/AdaptiveTree.cpp
Labels: Type: Fix, v20 Nexus

#1055 only set overallSeconds for non-subtitle playlists
  src/parser/HLSTree.cpp
Labels: Type: Fix, v20 Nexus

#1068 [SmoothStreaming] Use case-insensitive comparer for IsLive
  src/parser/SmoothTree.cpp
Labels: Type: Fix, v20 Nexus, Backport: Done, Component: SmoothStream

#1069 [SmoothStreaming] Use case-insensitive comparer for IsLive
  src/parser/SmoothTree.cpp
Labels: Type: Fix, v19 Matrix, Type: Backport, Component: SmoothStream
