Repository xbmc/inputstream.adaptive, pull requests merged in 2022-06, with the labels that each got.

#997 Refactor of Session class
  CMakeLists.txt
  src/KodiHost.cpp
  src/KodiHost.h
  src/Session.cpp
  src/Session.h
  src/Stream.cpp
  src/Stream.h
  src/main.cpp
  src/main.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/test/TestHLSTree.cpp
  src/test/TestHelper.cpp
  src/test/TestHelper.h
Labels: WIP, require discussion, v20 Nexus, RFC, Type: Cleanup

#998 Handle AES PKCS7 padding
  src/Iaes_decrypter.h
  src/aes_decrypter.cpp
  src/aes_decrypter.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/test/TestHelper.cpp
  src/test/TestHelper.h
Labels: Type: Fix, v20 Nexus, Component: HLS

#1001 Reinitialize cdm video decoder only when codec change
  src/SSD_dll.h
  src/common/AdaptiveDecrypter.h
  src/main.cpp
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  src/utils/log.h
  wvdecrypter/CMakeLists.txt
  wvdecrypter/Helper.cpp
  wvdecrypter/Helper.h
  wvdecrypter/cdm/media/cdm/cdm_adapter.cc
  wvdecrypter/cdm/media/cdm/cdm_adapter.h
  wvdecrypter/cdm/media/cdm/cdm_type_conversion.cc
  wvdecrypter/cdm/media/cdm/cdm_type_conversion.h
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: Type: Fix, v20 Nexus, Type: Cleanup

#1006 [utils][base64] Improved decoding
  src/utils/Base64Utils.cpp
  src/utils/Base64Utils.h
  wvdecrypter/CMakeLists.txt
Labels: v20 Nexus, Type: Improvement

#1002 Handle AES PKCS7 padding [Matrix]
  CMakeLists.txt
  src/Iaes_decrypter.h
  src/aes_decrypter.cpp
  src/aes_decrypter.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/main.cpp
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/test/TestHelper.cpp
  src/test/TestHelper.h
Labels: Type: Fix, v19 Matrix, Type: Backport, Component: HLS

#1010 Don't do PKCS7 stripping on chunked transfers
  src/common/AdaptiveStream.cpp
Labels: Type: Fix, v20 Nexus, Backport: Done, Component: HLS

#1011 [Backport] Don't do PKCS7 stripping on chunked transfers
  src/main.cpp
Labels: Type: Fix, v19 Matrix, Type: Backport, Component: HLS
