Repository xbmc/inputstream.adaptive, pull requests merged in 2022-03, with the labels that each got.

#911 GetNextSample: Avoid spam log when no sample reader exists
  src/main.cpp
Labels: Type: Fix, v20 Nexus

#912 [cleanup] Moved kodi properties parser to utils
  CMakeLists.txt
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/main.cpp
  src/main.h
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/parser/SmoothTree.cpp
  src/parser/SmoothTree.h
  src/test/CMakeLists.txt
  src/test/TestDASHTree.cpp
  src/test/TestHLSTree.cpp
  src/test/TestHelper.cpp
  src/test/TestHelper.h
  src/utils/PropertiesUtils.cpp
  src/utils/PropertiesUtils.h
Labels: v20 Nexus, Type: Cleanup

#914 [CI] Migrated to windows 2019 and VS 2019
  appveyor.yml
  azure-pipelines.yml
Labels: v20 Nexus, Component: Build

#913 [cleanup] Implemented UrlUtils and relative code cleanup
  CMakeLists.txt
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/main.cpp
  src/main.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/SmoothTree.cpp
  src/test/CMakeLists.txt
  src/test/TestDASHTree.cpp
  src/test/TestHLSTree.cpp
  src/test/TestHelper.cpp
  src/test/TestHelper.h
  src/utils/UrlUtils.cpp
  src/utils/UrlUtils.h
Labels: v20 Nexus, Type: Cleanup, Type: Improvement

#916 [cleanup] Cleanup to segment url and SPINCACHE
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/test/TestDASHTree.cpp
Labels: v20 Nexus, Type: Cleanup

#883 Begin refactor of wvdecrypter, sample-aes-cbc support
  CMakeLists.txt
  src/SSD_dll.h
  src/common/AdaptiveDecrypter.h
  src/main.cpp
  src/main.h
  wvdecrypter/cdm/media/cdm/cdm_adapter.cc
  wvdecrypter/cdm/media/cdm/cdm_adapter.h
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: v20 Nexus, Type: Cleanup, Type: Feature, DRM: Widevine

#917 [doc][cleanup] Readme cleanup
  README.md
Labels: v20 Nexus, Type: Cleanup, Component: Documentation

#873 On pre-init DRM still use the session opened
  src/SSD_dll.h
  src/common/AdaptiveDecrypter.h
  src/main.cpp
  src/main.h
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: Type: Fix, v20 Nexus, Backport: Needed

#921 [Backport] On pre-init DRM still use the session opened
  CMakeLists.txt
  src/SSD_dll.h
  src/common/AdaptiveDecrypter.h
  src/main.cpp
  src/main.h
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
  wvdecrypter/wvdecrypter_android_jni.cpp
Labels: Type: Fix, v19 Matrix, Type: Backport
