Repository xbmc/inputstream.adaptive, pull requests merged in 2022-04, with the labels that each got.

#927 Print a log warning for unsupported container/codec
  src/main.cpp
Labels: v20 Nexus, Type: Improvement

#924 [cleanup] Refactor of representation chooser
  CMakeLists.txt
  src/SSD_dll.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/common/RepresentationChooser.cpp
  src/common/RepresentationChooser.h
  src/common/RepresentationChooserDefault.cpp
  src/common/RepresentationChooserDefault.h
  src/main.cpp
  src/main.h
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/parser/SmoothTree.cpp
  src/parser/SmoothTree.h
  src/test/CMakeLists.txt
  src/test/TestDASHTree.cpp
  src/test/TestHLSTree.cpp
  src/test/TestHelper.cpp
  src/test/TestHelper.h
  src/utils/SettingsUtils.h
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: v20 Nexus, Type: Cleanup

#929 [cleanup] Removed KodiAdaptiveStream class
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/main.cpp
  src/main.h
  src/test/TestDASHTree.cpp
  src/test/TestHelper.h
Labels: v20 Nexus, Type: Cleanup

#925 Add add-on icon/fanart/info
  inputstream.adaptive/addon.xml.in
  inputstream.adaptive/fanart.jpg
  inputstream.adaptive/icon.png
Labels: v20 Nexus, Type: Improvement, Component: Documentation

#915 Refactor sample readers and AdaptiveByteStream into separate files
  CMakeLists.txt
  src/AdaptiveByteStream.cpp
  src/AdaptiveByteStream.h
  src/codechandler/AVCCodecHandler.h
  src/codechandler/HEVCCodecHandler.h
  src/codechandler/MPEGCodecHandler.h
  src/codechandler/TTMLCodecHandler.h
  src/codechandler/VP9CodecHandler.h
  src/codechandler/WebVTTCodecHandler.h
  src/main.cpp
  src/main.h
  src/samplereader/ADTSSampleReader.cpp
  src/samplereader/ADTSSampleReader.h
  src/samplereader/DummySampleReader.h
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/samplereader/TSSampleReader.cpp
  src/samplereader/TSSampleReader.h
  src/samplereader/WebmSampleReader.cpp
  src/samplereader/WebmSampleReader.h
Labels: v20 Nexus, Type: Cleanup

#933 Fix forced switch streams at video starts
  src/main.cpp
Labels: Type: Fix, v20 Nexus

#932 Representation chooser improvements and new settings
  CMakeLists.txt
  inputstream.adaptive/resources/language/resource.language.en_gb/strings.po
  inputstream.adaptive/resources/settings.xml.in
  src/AdaptiveByteStream.h
  src/aes_decrypter.h
  src/codechandler/CodecHandler.h
  src/codechandler/ttml/TTML.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/common/RepresentationChooser.cpp
  src/common/RepresentationChooser.h
  src/common/RepresentationChooserDefault.cpp
  src/common/RepresentationChooserDefault.h
  src/common/RepresentationChooserManualOSD.cpp
  src/common/RepresentationChooserManualOSD.h
  src/common/RepresentationSelector.cpp
  src/common/RepresentationSelector.h
  src/main.cpp
  src/main.h
  src/md5.h
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/parser/PRProtectionParser.h
  src/parser/SmoothTree.cpp
  src/parser/SmoothTree.h
  src/samplereader/SampleReader.h
  src/test/CMakeLists.txt
  src/test/KodiStubs.h
  src/test/TestDASHTree.cpp
  src/test/TestHLSTree.cpp
  src/test/TestHelper.cpp
  src/test/TestHelper.h
  src/utils/PropertiesUtils.cpp
  src/utils/PropertiesUtils.h
Labels: v20 Nexus, Type: Improvement, Wiki: Done

#940 Add stream_selection_type to allowed listitem props
  inputstream.adaptive/addon.xml.in
Labels: Type: Fix, v20 Nexus

#939 Moved HDCP check temporarily to AdaptiveTree
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/common/RepresentationChooser.h
  src/common/RepresentationChooserDefault.cpp
  src/common/RepresentationChooserDefault.h
  src/main.cpp
  src/main.h
  src/parser/DASHTree.cpp
  src/test/TestHelper.h
  wvdecrypter/wvdecrypter_android.cpp
Labels: v20 Nexus, Type: Cleanup

#941 Adaptive chooser improvements and cleanup
  CMakeLists.txt
  inputstream.adaptive/addon.xml.in
  inputstream.adaptive/resources/settings.xml.in
  src/common/RepresentationChooser.cpp
  src/common/RepresentationChooser.h
  src/common/RepresentationChooserDefault.cpp
  src/common/RepresentationChooserDefault.h
  src/common/RepresentationChooserManualOSD.cpp
  src/common/RepresentationChooserManualOSD.h
  src/test/CMakeLists.txt
  src/test/TestDASHTree.cpp
  src/test/TestHLSTree.cpp
  src/test/TestHelper.h
  src/utils/PropertiesUtils.cpp
  src/utils/PropertiesUtils.h
  src/utils/SettingsUtils.cpp
  src/utils/SettingsUtils.h
Labels: v20 Nexus, Type: Cleanup, Type: Improvement, Wiki: Done

#943 Some build warning fixes
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/common/RepresentationSelector.cpp
  src/main.cpp
  src/parser/HLSTree.h
  src/samplereader/FragmentedSampleReader.h
  src/utils/log.h
  wvdecrypter/cdm/media/cdm/cdm_adapter.h
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: v20 Nexus, Type: Cleanup

#942 New representation choosers: Fixed resolution / Ask quality
  CMakeLists.txt
  inputstream.adaptive/resources/language/resource.language.en_gb/strings.po
  inputstream.adaptive/resources/settings.xml.in
  src/common/RepresentationChooser.cpp
  src/common/RepresentationChooserAskQuality.cpp
  src/common/RepresentationChooserAskQuality.h
  src/common/RepresentationChooserFixedRes.cpp
  src/common/RepresentationChooserFixedRes.h
  src/common/RepresentationSelector.cpp
  src/common/RepresentationSelector.h
  src/test/CMakeLists.txt
  src/test/KodiStubs.h
  src/utils/Utils.cpp
  src/utils/Utils.h
Labels: v20 Nexus, Type: Feature, Wiki: Done

#947 Fix webvtt/mp4 subtitles crash
  src/parser/WebVTT.cpp
Labels: Type: Fix, v19 Matrix, Component: Subtitles

#950 Get max bandwidth on Highest selector
  src/common/RepresentationSelector.cpp
Labels: v20 Nexus, Type: Improvement

#951 Add new "Test" chooser representation
  CMakeLists.txt
  inputstream.adaptive/resources/language/resource.language.en_gb/strings.po
  inputstream.adaptive/resources/settings.xml.in
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/Chooser.cpp
  src/common/Chooser.h
  src/common/ChooserAskQuality.cpp
  src/common/ChooserAskQuality.h
  src/common/ChooserDefault.cpp
  src/common/ChooserDefault.h
  src/common/ChooserFixedRes.cpp
  src/common/ChooserFixedRes.h
  src/common/ChooserManualOSD.cpp
  src/common/ChooserManualOSD.h
  src/common/ChooserTest.cpp
  src/common/ChooserTest.h
  src/common/ReprSelector.cpp
  src/common/ReprSelector.h
  src/main.h
  src/test/CMakeLists.txt
  src/test/TestHelper.h
Labels: v20 Nexus, Type: Feature

#953 [cleanup] Cleanup and moved md5 to utils
  CMakeLists.txt
  src/md5.cpp
  src/md5.h
  src/utils/DigestMD5Utils.cpp
  src/utils/DigestMD5Utils.h
  wvdecrypter/CMakeLists.txt
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: v20 Nexus, Type: Cleanup

#954 Fixed estimate segments count method
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
Labels: Type: Fix, v20 Nexus, Backport: Needed

#955 [chooser][askquality] Show fps value on stream info
  src/common/ChooserAskQuality.cpp
Labels: v20 Nexus, Type: Improvement

#957 [backport] Fixed estimate segments count method
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
Labels: Type: Fix, v19 Matrix, Type: Backport
