Repository xbmc/inputstream.adaptive, pull requests merged in 2022-07, with the labels that each got.

#1009 [DASH] Fix SegmentList in period
  src/parser/DASHTree.cpp
Labels: Type: Fix, v20 Nexus

#1008 Send empty packets instead of blocking DemuxRead
  CMakeLists.txt
  src/Session.cpp
  src/Session.h
  src/Stream.cpp
  src/main.cpp
  src/samplereader/DummySampleReader.h
  src/samplereader/SampleReader.h
Labels: Type: Fix, v20 Nexus

#1014 [Subtitles][WebVTT] Sync to current period start (chapter)
  CMakeLists.txt
  src/main.cpp
  src/samplereader/SampleReader.h
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/utils/FFmpeg.h
  src/utils/MemUtils.cpp
  src/utils/MemUtils.h
Labels: Type: Fix, v20 Nexus, Component: Subtitles

#1017 Switched bento4 sources to xbmc fork
  depends/common/bento4/0001-Add-additional-methods-funtions-and-passing-poolid.patch
  depends/common/bento4/0002-Backport-Smmothstream-changes.patch
  depends/common/bento4/0003-more-SPS-parameters.patch
  depends/common/bento4/0004-AVC-extract-VUI-values-from-SPS.patch
  depends/common/bento4/0005-Implement-SPS-Frame-parser.patch
  depends/common/bento4/0006-Fix-segfault-when-AP4_Sample-s-seek.patch
  depends/common/bento4/0007-Hack-HBO.patch
  depends/common/bento4/0008-Android-32-ftello-fix.patch
  depends/common/bento4/0009-Dazn-sample-duration-workaround.patch
  depends/common/bento4/0010-Add-argument-to-reuse-single-sample-decrypter.patch
  depends/common/bento4/0011-Static-ReadGolomb-SignedGolomb.patch
  depends/common/bento4/0012-Add-GetChannels-method.patch
  depends/common/bento4/0013-Implemented-GetSampleIndexForTimeStamp-GetNearestSyn.patch
  depends/common/bento4/0014-Ap4SampleDescription-added-missing-dynamic-casts.patch
  depends/common/bento4/0015-Avoid-set-next-fragment-position.patch
  depends/common/bento4/0016-Add-support-for-cmake-install.patch
  depends/common/bento4/0017-Add-GetData-atom-uuid-vpcc.patch
  depends/common/bento4/0991-Check-for-null-descriptor.patch
  depends/common/bento4/0992-Update-m_sampleCount-after-successfully-reading-in-m.patch
  depends/common/bento4/0993-set-m_SampleCount-even-when-m_SampleSize-0.patch
  depends/common/bento4/0995-CVE-2019-17452.patch
  depends/common/bento4/0996-fix-663.patch
  depends/common/bento4/0997-fix-679.patch
  depends/common/bento4/0998-CVE-2021-32265.patch
  depends/common/bento4/bento4.sha256
  depends/common/bento4/bento4.txt
Labels: v20 Nexus, Component: Depends

#1022 Fix condition check for chunked transfers
  src/common/AdaptiveStream.cpp
Labels: Type: Fix, v20 Nexus

#1025 [Backport] Fix condition check for chunked transfers
  src/main.cpp
Labels: Type: Fix, v19 Matrix, Type: Backport
