Repository xbmc/inputstream.adaptive, pull requests merged in 2022-05, with the labels that each got.

#959 [chooser] Merged ChooseRepresentation with ChooseNextRepresentation
  src/common/AdaptiveStream.cpp
  src/common/Chooser.cpp
  src/common/Chooser.h
  src/common/ChooserAskQuality.cpp
  src/common/ChooserAskQuality.h
  src/common/ChooserDefault.cpp
  src/common/ChooserDefault.h
  src/common/ChooserFixedRes.cpp
  src/common/ChooserFixedRes.h
  src/common/ChooserManualOSD.cpp
  src/common/ChooserManualOSD.h
  src/common/ChooserTest.cpp
  src/common/ChooserTest.h
  src/main.cpp
  src/test/TestDASHTree.cpp
Labels: Type: Fix, v20 Nexus, Type: Improvement

#887 Send mode and pattern with demux packets
  src/common/AdaptiveDecrypter.h
  src/main.cpp
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  wvdecrypter/wvdecrypter.cpp
Labels: v20 Nexus, DRM: Widevine, DRM: PlayReady

#960 [DigestMD5Utils] Moved operator in header to remove warning
  src/utils/DigestMD5Utils.cpp
  src/utils/DigestMD5Utils.h
Labels: v20 Nexus, Type: Cleanup

#962 [cleanup] Removed CheckHDCP from RefreshLiveSegments
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
Labels: v20 Nexus, Type: Cleanup

#965 [StringUtils] Fix URLEncode wrong hexdecimal
  src/utils/StringUtils.cpp
Labels: Type: Fix, v20 Nexus

#966 Fix wrong char position parsing license placeholder
  wvdecrypter/wvdecrypter.cpp
Labels: Type: Fix, v20 Nexus

#970 [HEVCCodec] Fix wrong foreach loops for extradata
  src/codechandler/HEVCCodecHandler.cpp
Labels: Type: Fix, v20 Nexus

#980 Updated and fixed codecs in SSD interface
  src/SSD_dll.h
  wvdecrypter/wvdecrypter.cpp
Labels: Type: Fix, v20 Nexus

#971 [bento4] Fix VP9 GetData for metadata
  depends/common/bento4/0001-Add-additional-methods-funtions-and-passing-poolid.patch
  depends/common/bento4/0017-Add-GetData-atom-uuid-vpcc.patch
Labels: Type: Fix, v20 Nexus, Component: Depends

#981 [Backport] Updated and fixed codecs in SSD interface
  src/SSD_dll.h
  wvdecrypter/wvdecrypter.cpp
Labels: Type: Fix, v19 Matrix, Type: Backport

#984 Fix FourCC creation
  src/utils/Utils.h
Labels: Type: Fix, v20 Nexus

#988 Set byteranged init segments explicitly
  src/parser/HLSTree.cpp
Labels: Type: Fix, v19 Matrix, Type: Backport

#986 Set byteranged init segments explicitly
  src/parser/HLSTree.cpp
Labels: Type: Fix, v20 Nexus, Backport: Done

#994 Fixed parsing of stream_selection_type property
  src/utils/PropertiesUtils.cpp
Labels: Type: Fix, v20 Nexus
