Repository xbmc/inputstream.adaptive, pull requests merged in 2022-02, with the labels that each got.

#892 Codechandler refactor
  CMakeLists.txt
  src/codechandler/AVCCodecHandler.cpp
  src/codechandler/AVCCodecHandler.h
  src/codechandler/CodecHandler.cpp
  src/codechandler/CodecHandler.h
  src/codechandler/HEVCCodecHandler.cpp
  src/codechandler/HEVCCodecHandler.h
  src/codechandler/MPEGCodecHandler.cpp
  src/codechandler/MPEGCodecHandler.h
  src/codechandler/TTMLCodecHandler.cpp
  src/codechandler/TTMLCodecHandler.h
  src/codechandler/VP9CodecHandler.cpp
  src/codechandler/VP9CodecHandler.h
  src/codechandler/WebVTTCodecHandler.cpp
  src/codechandler/WebVTTCodecHandler.h
  src/codechandler/ttml/TTML.cpp
  src/codechandler/ttml/TTML.h
  src/main.cpp
Labels: v20 Nexus, Type: Cleanup

#898 Fix for streams containing multiple $RepresentationID$ in URL
  src/parser/DASHTree.cpp
Labels: Type: Fix, v20 Nexus, Backport: Done

#899 Fix for streams containing multiple $RepresentationID$ in URL
  src/parser/DASHTree.cpp
Labels: Type: Fix, v19 Matrix, Type: Backport

#901 Refactor generic helpers to new utils
  CMakeLists.txt
  src/SSD_dll.h
  src/codechandler/HEVCCodecHandler.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/RepresentationChooser.cpp
  src/helpers.cpp
  src/helpers.h
  src/log.h
  src/main.cpp
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/PRProtectionParser.cpp
  src/parser/SmoothTree.cpp
  src/test/CMakeLists.txt
  src/test/TestHelper.cpp
  src/test/TestHelper.h
  src/utils/Base64Utils.cpp
  src/utils/Base64Utils.h
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
  src/utils/Utils.cpp
  src/utils/Utils.h
  src/utils/log.h
  wvdecrypter/CMakeLists.txt
  wvdecrypter/cdm/media/cdm/cdm_adapter.cc
  wvdecrypter/cdm/media/cdm/cdm_adapter.h
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: v20 Nexus, Type: Cleanup

#907 Update some pointers to use smart pointers
  src/main.cpp
  src/main.h
Labels: v20 Nexus, Type: Cleanup
