Repository xbmc/inputstream.adaptive, pull requests merged in 2022-01, with the labels that each got.

#857 [WebVTT] Read only payl box for text
  src/parser/WebVTT.cpp
  src/parser/WebVTT.h
Labels: Type: Fix, v19 Matrix, Component: Subtitles

#872 [Matrix] Remove duplicate seektime call
  src/main.cpp
Labels: Type: Fix, v19 Matrix

#875 [WebVTT] Fix sending segments packages
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.h
  src/main.cpp
  src/parser/HLSTree.cpp
Labels: Type: Fix, Component: Subtitles

#878 Fix for huge media sequence numbers
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
Labels: Type: Fix, v20 Nexus

#891 [Matrix] fix for large media sequences
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
Labels: Type: Fix, v19 Matrix, Type: Backport
