Repository xbmc/inputstream.adaptive, pull requests merged in 2023-05, with the labels that each got.

#1249 [HLSTree] Fix wrong saved manifest child filename
  src/parser/HLSTree.cpp
Labels: Type: Fix, Component: HLS, v21 Omega

#1246 [PropertiesUtils] Add live_delay property
  inputstream.adaptive/addon.xml.in
  src/Session.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/utils/PropertiesUtils.cpp
  src/utils/PropertiesUtils.h
Labels: Backport: Done, Type: Feature, v21 Omega

#1247 [backport][PropertiesUtils] Add live_delay property
  inputstream.adaptive/addon.xml.in
  src/Session.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/utils/PropertiesUtils.cpp
  src/utils/PropertiesUtils.h
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
Labels: v20 Nexus, Type: Backport, Type: Feature

#1252 [DASHTree] Convert codecPrivateData to avc
  src/parser/DASHTree.cpp
Labels: Type: Fix, v21 Omega

#1255 [DASHTree] Fix timescale on SegmentList
  src/parser/DASHTree.cpp
Labels: Type: Fix, v21 Omega

#1257 [SubtitleSampleReader] Fixed m_codecHandler memory leak
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
Labels: Type: Fix, v20 Nexus

#1256 [Nexus][AdaptiveTree] Fix memory leak
  src/common/AdaptiveTree.h
Labels: Type: Fix, v20 Nexus

#1261 [WebmReader] Parse audio track extradata
  src/WebmReader.cpp
Labels: Type: Fix, v21 Omega

#1268 [AdaptiveTree] Move update thread start to PostOpen
  src/common/AdaptiveTree.cpp
  src/parser/DASHTree.cpp
Labels: Type: Fix, Backport: Done, v21 Omega

#1269 [Backport] [Nexus] Move update thread start to PostOpen
  src/common/AdaptiveTree.cpp
  src/parser/DASHTree.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1239 CInputStreamAdaptive: use std::map for m_IncludedStreams
  src/main.cpp
  src/main.h
Labels: Type: Fix, v21 Omega

#1275 [DASHTree] Allow content protection without systemid urn
  src/Session.cpp
  src/parser/DASHTree.cpp
Labels: Type: Fix, v21 Omega
