Repository xbmc/inputstream.adaptive, pull requests merged in 2023-12, with the labels that each got.

#1427 [DashTree] Fix segment end number wrong condition
  src/parser/DASHTree.cpp
Labels: Type: Fix, v20 Nexus

#1428 [HLSTree] Fix empty audio codec
  src/parser/HLSTree.cpp
Labels: Type: Fix, v21 Omega

#1399 [Properties] Add license_url/license_url_append properties
  inputstream.adaptive/addon.xml.in
  src/CompKodiProps.cpp
Labels: Backport: Done, Type: Improvement, Wiki: Done, v21 Omega

#1424 [backport][Properties] Add license_url/license_url_append properties
  inputstream.adaptive/addon.xml.in
  src/utils/PropertiesUtils.cpp
Labels: v20 Nexus, Type: Backport, Type: Improvement

#1412 Workaround to keep in memory cookies between http sessions
  inputstream.adaptive/addon.xml.in
  src/CMakeLists.txt
  src/CompKodiProps.cpp
  src/CompKodiProps.h
  src/CompResources.h
  src/SrvBroker.cpp
  src/SrvBroker.h
  src/utils/CurlUtils.cpp
  src/utils/CurlUtils.h
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
  src/utils/UrlUtils.cpp
  src/utils/UrlUtils.h
Labels: Type: Fix, Wiki: Done, v21 Omega

#1430 [HLSTree] Fix check for EXTM3U on child playlist
  src/parser/HLSTree.cpp
Labels: Type: Fix, v21 Omega

#1431 [HLSTree] Dont overwrite interval value
  src/parser/HLSTree.cpp
Labels: Type: Fix, v21 Omega

#1433 [Settings] Lowered minimum initial bandwidth value to 50kbps
  inputstream.adaptive/resources/settings.xml.in
Labels: Backport: Done, Type: Improvement, v21 Omega

#1434 [backport][Settings] Lowered minimum initial bandwidth value to 50kbps
  inputstream.adaptive/resources/settings.xml.in
Labels: v20 Nexus, Type: Backport, Type: Improvement

#1435 [Readme] Wiki page for addon WIP status
  README.md
Labels: Documentation, v21 Omega

#1436 build_config.h: Add LoongArch support
  lib/cdm/cdm/build/build_config.h
Labels: Backport: Needed, Type: Improvement, Component: Build, v21 Omega

#1437 [backport][Github/Workflow] Changed version / news default values
  .github/workflows/changelog-and-release.yml
Labels: v20 Nexus, Type: Backport

#1441 [backport][UrlUtils] Increased the url size limit to 8000 chars
  src/utils/UrlUtils.cpp
Labels: v20 Nexus, Type: Backport, Type: Improvement

#1442 [UrlUtils] Increased the url size limit to 8000 chars
  src/utils/UrlUtils.cpp
Labels: Backport: Done, Type: Improvement, v21 Omega

#1439 [decrypters] Various cleanups to interface
  src/Session.cpp
  src/Session.h
  src/decrypters/IDecrypter.h
  src/decrypters/widevine/WVCdmAdapter.cpp
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevine/WVDecrypter.cpp
  src/decrypters/widevine/WVDecrypter.h
  src/decrypters/widevineandroid/WVCdmAdapter.cpp
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVDecrypter.cpp
  src/decrypters/widevineandroid/WVDecrypter.h
  src/main.cpp
  src/utils/CurlUtils.cpp
  src/utils/FileUtils.cpp
  src/utils/FileUtils.h
Labels: Type: Cleanup, v21 Omega
