Repository xbmc/inputstream.adaptive, pull requests merged in 2023-07, with the labels that each got.

#1302 Fix ways to update manifest and intervals
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/test/TestDASHTree.cpp
  src/test/TestHelper.cpp
  src/test/TestHelper.h
Labels: Type: Fix, v21 Omega

#1305 [HLSTree] Fix get VP9 codec name
  src/parser/HLSTree.cpp
Labels: Type: Fix, v20 Nexus, Component: HLS

#1309 [HLSTree] Fix wrong range end byte
  src/parser/HLSTree.cpp
Labels: Type: Fix, Component: HLS, v21 Omega

#1307 [AdaptiveTree] Removed uses of HasSegmentUrl
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/Representation.cpp
  src/common/Representation.h
  src/common/Segment.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
Labels: Type: Cleanup, v21 Omega

#1310 [FragmSampleReader] Removed extra memory reserved
  src/samplereader/FragmentedSampleReader.cpp
Labels: Type: Cleanup, v21 Omega

#1313 [backport][AdaptiveTree] Preserve path to save manifest on cloning class
  src/common/AdaptiveTree.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1312 [AdaptiveTree] Preserve path to save manifest on cloning class
  src/common/AdaptiveTree.cpp
Labels: Type: Fix, Backport: Done, v21 Omega

#1316 [DashTree] Fix replaced init segment from SegmentTemplate
  src/parser/DASHTree.cpp
Labels: Type: Fix, v21 Omega

#1320 [backport][DASHTree] Dont force rounding segment count
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1321 [HLSTree] Fix get file extension from segment url
  src/parser/HLSTree.cpp
  src/utils/UrlUtils.cpp
  src/utils/UrlUtils.h
Labels: Type: Fix, v21 Omega

#1318 [Cleanup] Use vector uint8_t to store data
  src/Iaes_decrypter.h
  src/aes_decrypter.cpp
  src/aes_decrypter.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/test/TestHelper.cpp
  src/test/TestHelper.h
Labels: Type: Cleanup, v21 Omega

#1323 Fixes for buffer and recent regressions
  inputstream.adaptive/resources/settings.xml.in
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/main.cpp
Labels: Type: Fix, v21 Omega

#1322 [AdaptiveStream] On ResetSegment check for byterange not url
  src/common/AdaptiveStream.cpp
Labels: Type: Fix, v21 Omega

#1325 [SmoothTree] Regression fixes and better logging
  src/Session.cpp
  src/Session.h
  src/Stream.cpp
  src/Stream.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/common/SegTemplate.cpp
  src/common/SegTemplate.h
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/SmoothTree.cpp
  src/parser/SmoothTree.h
  src/samplereader/ADTSSampleReader.h
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  src/samplereader/SubtitleSampleReader.h
  src/samplereader/TSSampleReader.h
  src/samplereader/WebmSampleReader.h
  src/test/KodiStubs.h
  src/test/TestSmoothTree.cpp
  src/test/TestUtils.cpp
  src/test/manifests/ism/live_async_streams.ism
  src/utils/CharArrayParser.cpp
  src/utils/CharArrayParser.h
Labels: Type: Fix, Type: Cleanup, Component: SmoothStream, v21 Omega

#1328 [HLSTree] Fix missing codec for media playlist
  src/parser/HLSTree.cpp
Labels: Type: Fix, v21 Omega

#1329 [backport] Fallback to ADTS sample reader when TS initialization fails
  src/main.cpp
Labels: Type: Fix, v20 Nexus, Type: Partial backport

#1336 [backport] include missing <cstdint> to support gcc-13
  src/Iaes_decrypter.h
  src/SSD_dll.h
  src/utils/FileUtils.h
  src/utils/PropertiesUtils.h
  src/utils/StringUtils.h
  src/utils/Utils.h
Labels: Type: Fix, v20 Nexus, Type: Partial backport, Component: Build

#1330 [codechandler] Check and correct stream codec info
  CMakeLists.txt
  src/ADTSReader.cpp
  src/ADTSReader.h
  src/Session.cpp
  src/TSReader.cpp
  src/WebmReader.cpp
  src/WebmReader.h
  src/codechandler/AV1CodecHandler.cpp
  src/codechandler/AVCCodecHandler.cpp
  src/codechandler/AudioCodecHandler.cpp
  src/codechandler/AudioCodecHandler.h
  src/codechandler/CodecHandler.cpp
  src/codechandler/CodecHandler.h
  src/codechandler/HEVCCodecHandler.cpp
  src/codechandler/MPEGCodecHandler.cpp
  src/codechandler/VP9CodecHandler.cpp
  src/codechandler/VP9CodecHandler.h
  src/common/Representation.cpp
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/samplereader/FragmentedSampleReader.cpp
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
  src/utils/Utils.cpp
  src/utils/Utils.h
Labels: Type: Fix, Type: Improvement, v21 Omega

#1338 [cleanup] some code cleanup
  src/common/AdaptationSet.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/common/Representation.cpp
  src/main.cpp
  src/parser/HLSTree.cpp
  src/samplereader/SubtitleSampleReader.cpp
  src/test/TestHLSTree.cpp
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
  src/utils/Utils.cpp
Labels: Type: Cleanup, v21 Omega

#1339 [DashTree] Cleanup subtitles stream/container detection
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/utils/Utils.cpp
  src/utils/Utils.h
Labels: Type: Fix, Type: Cleanup, v21 Omega

#1340 [AdaptiveTree] Add missing impaired cases to dash/hls
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
Labels: Type: Improvement, v21 Omega
