Repository xbmc/inputstream.adaptive, pull requests merged in 2023-02, with the labels that each got.

#1113 Improved logging during capabilities probe
  wvdecrypter/wvdecrypter.cpp
Labels: v20 Nexus, Type: Improvement

#1119 [AdaptiveStream] Fix IV decrypter, range format regressions
  src/aes_decrypter.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
Labels: Type: Fix, v20 Nexus

#1082 Fix seek audio/video, various subtitle fixes
  src/Session.cpp
  src/Session.h
  src/TSReader.cpp
  src/TSReader.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/main.cpp
  src/parser/HLSTree.cpp
  src/samplereader/ADTSSampleReader.h
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/samplereader/TSSampleReader.cpp
  src/samplereader/TSSampleReader.h
  src/samplereader/WebmSampleReader.h
  src/test/TestHLSTree.cpp
Labels: Type: Fix, v20 Nexus

#1092 FragmentedSampleReader: prevent crash if track is not present in reader
  src/samplereader/FragmentedSampleReader.cpp
Labels: Type: Fix, v20 Nexus

#1123 [GitHub] Add Pull Request template
  .github/pull_request_template.md
Labels: v20 Nexus, Type: Cleanup

#1122 [workflows][build] Updated ubuntu/macos images
  .github/workflows/build.yml
Labels: Type: Fix, v20 Nexus, Component: Build

#1120 [Bento4] Version bump 1.6.0-639-6-Nexus
  depends/common/bento4/bento4.sha256
  depends/common/bento4/bento4.txt
Labels: v20 Nexus, Type: Improvement, Component: Depends

#1125 [DASHTree] Enable manifest update for representations with SegmentTimeline
  src/parser/DASHTree.cpp
Labels: Type: Fix, v20 Nexus, Component: MPEG-DASH

#1126 ChooserDefault: initialize "limited" bandwidth if automatic turned off
  src/common/ChooserDefault.cpp
Labels: Type: Fix, v20 Nexus

#1135 [SampleReader] Removed use of subtitle demux packet sidedata
  src/main.cpp
  src/samplereader/SampleReader.h
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
Labels: Type: Cleanup, v21 Omega

#1136 Removed features marked as deprecated on Kodi 20
  inputstream.adaptive/addon.xml.in
  src/main.cpp
  src/utils/PropertiesUtils.cpp
Labels: Type: Breaking change, v21 Omega

#1133 [AdaptiveStream] Restored decrypter IV variable as class member
  src/aes_decrypter.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
Labels: Type: Fix, Backport: Needed, Component: HLS, v21 Omega

#1139 [utils] Remove ffmpeg header
  CMakeLists.txt
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/utils/FFmpeg.h
Labels: Type: Cleanup, v21 Omega

#1141 [backport][AdaptiveStream] Restored decrypter IV variable as class member
  src/aes_decrypter.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
Labels: Type: Fix, v20 Nexus, Type: Backport, Component: HLS

#1140 [AdaptiveTree] Implemented save manifest setting for debug
  CMakeLists.txt
  inputstream.adaptive/resources/language/resource.language.en_gb/strings.po
  inputstream.adaptive/resources/settings.xml.in
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/parser/SmoothTree.cpp
  src/test/CMakeLists.txt
  src/test/KodiStubs.h
  src/utils/FileUtils.cpp
  src/utils/FileUtils.h
  src/utils/Utils.cpp
  src/utils/Utils.h
Labels: Backport: Done, Type: Feature, v21 Omega

#1150 [backport][AdaptiveTree] Implemented save manifest setting for debug
  CMakeLists.txt
  inputstream.adaptive/resources/language/resource.language.en_gb/strings.po
  inputstream.adaptive/resources/settings.xml.in
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/parser/SmoothTree.cpp
  src/test/CMakeLists.txt
  src/test/KodiStubs.h
  src/utils/FileUtils.cpp
  src/utils/FileUtils.h
  src/utils/Utils.cpp
  src/utils/Utils.h
Labels: v20 Nexus, Type: Backport, Type: Feature

#1151 [UrlUtils] Fixed methods to follow RFC 3986
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/test/CMakeLists.txt
  src/test/TestDASHTree.cpp
  src/test/TestUtils.cpp
  src/utils/UrlUtils.cpp
  src/utils/UrlUtils.h
Labels: Type: Fix, Backport: Needed, v21 Omega

#1157 [backport][UrlUtils] Fixed methods to follow RFC 3986
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/test/CMakeLists.txt
  src/test/TestDASHTree.cpp
  src/test/TestUtils.cpp
  src/utils/UrlUtils.cpp
  src/utils/UrlUtils.h
Labels: Type: Fix, v20 Nexus, Type: Backport

#1158 [Session] Fix set init data from license data property
  src/Session.cpp
Labels: Type: Fix, Backport: Done, v21 Omega

#1159 [backport][Session] Fix set init data from license data property
  src/Session.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1164 [DASHTree] fix representation updates when two identical adaptation sets exist
  src/parser/DASHTree.cpp
Labels: Type: Fix, Backport: Done, v21 Omega

#1167 [backport] [DASHTree] fix representation updates when two identical adaptation sets exist
  src/parser/DASHTree.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1163 [SSD] Re-implemented save license data as debug setting
  inputstream.adaptive/resources/language/resource.language.en_gb/strings.po
  inputstream.adaptive/resources/settings.xml.in
  src/KodiHost.h
  src/SSD_dll.h
  src/Session.cpp
  wvdecrypter/Helper.cpp
  wvdecrypter/Helper.h
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: Backport: Needed, Type: Feature, v21 Omega

#1130 [backport][widevine] add support for linux arm64
  src/Session.cpp
  wvdecrypter/wvdecrypter.cpp
Labels: v20 Nexus, Type: Backport, Type: Improvement, DRM: Widevine

#1166 [widevine] add support for linux arm64
  src/Session.cpp
  wvdecrypter/wvdecrypter.cpp
Labels: Backport: Done, Type: Improvement, DRM: Widevine, v21 Omega

#1171 [DASHTree] Ensure backslash to baseurl outside period
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/segtpl_baseurl_noslash_outside.mpd
Labels: Type: Fix, Backport: Done, Component: MPEG-DASH, v21 Omega

#1172 [backport][DASHTree] Ensure backslash to baseurl outside period
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/segtpl_baseurl_noslash_outside.mpd
Labels: Type: Fix, v20 Nexus, Type: Backport, Component: MPEG-DASH
