Repository xbmc/inputstream.adaptive, pull requests merged in 2023-04, with the labels that each got.

#1206 [Backport] [Nexus] Fix CDM timer issues
  wvdecrypter/cdm/media/cdm/cdm_adapter.cc
  wvdecrypter/cdm/media/cdm/cdm_adapter.h
Labels: Type: Fix, v20 Nexus, Type: Backport, DRM: Widevine

#1203 Fix CDM timer issues
  wvdecrypter/cdm/media/cdm/cdm_adapter.cc
  wvdecrypter/cdm/media/cdm/cdm_adapter.h
Labels: Type: Fix, Backport: Done, Type: Improvement, DRM: Widevine, v21 Omega

#1210 [AdaptiveStream] Fix unreleased mutex and a/v freeze
  src/Stream.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/samplereader/SubtitleSampleReader.cpp
Labels: Type: Fix, Backport: Needed, v21 Omega

#1211 [backport][AdaptiveStream] Fix unreleased mutex and a/v freezes
  src/Stream.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/samplereader/SubtitleSampleReader.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1214 [CodecHandler] Reworked TTML parser
  src/codechandler/TTMLCodecHandler.cpp
  src/codechandler/ttml/TTML.cpp
  src/codechandler/ttml/TTML.h
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
Labels: Type: Improvement, v21 Omega

#1215 [FragmentedSampleReader] Ensure m_timeBaseInt is > 0
  src/samplereader/FragmentedSampleReader.cpp
Labels: Type: Fix, v21 Omega

#1218 [deps] Removed expat dependency
  CMakeLists.txt
  debian/control
  depends/common/expat/CMakeLists.txt
  depends/common/expat/expat.sha256
  depends/common/expat/expat.txt
  depends/windows/expat/expat.sha256
  depends/windows/expat/expat.txt
  depends/windows/expat/flags.txt
  depends/windowsstore/expat/expat.sha256
  depends/windowsstore/expat/expat.txt
  depends/windowsstore/expat/flags.txt
  src/test/CMakeLists.txt
Labels: Type: Cleanup, Component: Depends, v21 Omega

#1220 [AdaptiveStream] Add class id for debug log purpose
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveUtils.cpp
  src/common/AdaptiveUtils.h
  src/parser/HLSTree.cpp
Labels: Type: Improvement, v21 Omega

#1165 [DRM] Revert to single session decryption (when possible)
  CMakeLists.txt
  depends/common/bento4/bento4.sha256
  depends/common/bento4/bento4.txt
  src/Session.cpp
  src/common/AdaptiveCencSampleDecrypter.cpp
  src/common/AdaptiveCencSampleDecrypter.h
  src/common/AdaptiveDecrypter.h
  src/common/AdaptiveTree.h
  src/common/Period.h
  src/main.cpp
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  src/utils/CryptoUtils.h
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: Type: Fix, Backport: Done, DRM: Widevine, DRM: PlayReady, v21 Omega

#1219 Fix audio / subtitles regressions
  src/Session.cpp
  src/common/AdaptationSet.h
  src/common/AdaptiveStream.cpp
  src/common/Representation.h
  src/main.cpp
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/test/TestDASHTree.cpp
Labels: Type: Fix, Component: Audio, Component: Subtitles, v21 Omega

#1221 [AdaptiveStream] Fix tree mutex deadlock
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
Labels: Type: Fix, Backport: Needed, v21 Omega

#1225 [AdaptiveStream] Dont lock mutex_rw_ for nothing
  src/common/AdaptiveStream.cpp
Labels: v20 Nexus, Type: Improvement, Type: Partial backport

#1224 [backport][AdaptiveStream] Fix tree mutex deadlock
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1226 [AdaptiveTree] Removed update thread pointer
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
Labels: Backport: Needed, Type: Cleanup, v21 Omega

#1227 [backport][AdaptiveTree] Removed update thread pointer
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
Labels: v20 Nexus, Type: Backport, Type: Cleanup

#1222 [AdaptiveStream] Cleanup download methods
  CMakeLists.txt
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/test/CMakeLists.txt
  src/test/TestHelper.cpp
  src/test/TestHelper.h
  src/utils/CurlUtils.cpp
  src/utils/CurlUtils.h
Labels: Type: Cleanup, Type: Improvement, v21 Omega

#1233 Cleanup AdaptiveTree/SubtitleSampleReader download methods
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/HLSTree.cpp
  src/samplereader/SubtitleSampleReader.cpp
  src/test/TestHelper.cpp
  src/test/TestHelper.h
  src/utils/CurlUtils.cpp
  src/utils/CurlUtils.h
Labels: Type: Cleanup, v21 Omega

#1229 [SmoothStreaming] Cleanups and fix loading of PlayReady header data
  CMakeLists.txt
  src/parser/PRProtectionParser.cpp
  src/parser/PRProtectionParser.h
  src/parser/SmoothTree.cpp
  src/parser/SmoothTree.h
  src/test/CMakeLists.txt
  src/utils/CharArrayParser.cpp
  src/utils/CharArrayParser.h
Labels: Type: Fix, Type: Cleanup, Component: SmoothStream, v21 Omega

#1235 [AdaptiveCencSampleDecrypter] Removed Adaptive_CencSingleSampleDecrypter downcast
  src/common/AdaptiveCencSampleDecrypter.cpp
  src/common/AdaptiveCencSampleDecrypter.h
Labels: Type: Fix, Backport: Needed, v21 Omega

#1237 [AdaptiveTree] Some cleanups after refactor
  src/Session.cpp
  src/common/AdaptationSet.cpp
  src/common/AdaptationSet.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/parser/SmoothTree.cpp
Labels: Type: Cleanup, v21 Omega

#1216 [Backport] [Nexus] Revert to single wv session
  CMakeLists.txt
  depends/common/bento4/bento4.sha256
  depends/common/bento4/bento4.txt
  src/Session.cpp
  src/common/AdaptiveCencSampleDecrypter.cpp
  src/common/AdaptiveCencSampleDecrypter.h
  src/common/AdaptiveDecrypter.h
  src/common/AdaptiveTree.h
  src/main.cpp
  src/parser/DASHTree.cpp
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  src/utils/CryptoUtils.h
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport, DRM: Widevine, DRM: PlayReady

#1238 [AdaptiveTree] Fix buffer data for goolge tests
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/test/TestHelper.cpp
Labels: Type: Fix, v21 Omega

#1240 include missing <cstdint> to support gcc-13
  src/Iaes_decrypter.h
  src/SSD_dll.h
  src/utils/FileUtils.h
  src/utils/PropertiesUtils.h
  src/utils/StringUtils.h
  src/utils/Utils.h
  src/utils/XMLUtils.h
Labels: Type: Fix, Component: Build, v21 Omega

#1241 [ADTS] - Initialise pts
  src/ADTSReader.h
Labels: Type: Fix, Backport: Done, v21 Omega

#1243 [backport] [ADTS] - Initialise pts
  src/ADTSReader.h
Labels: Type: Fix, v20 Nexus, Type: Backport

#1244 [DASH] parse encryption scheme value
  src/parser/DASHTree.cpp
Labels: Backport: Done, Type: Improvement, DRM: Widevine, v21 Omega
