Repository xbmc/inputstream.adaptive, pull requests merged in 2023-11, with the labels that each got.

#1411 [cleanups] Cleanups to includes and minor things
  lib/webm_parser/src/master_parser.h
  src/AdaptiveByteStream.cpp
  src/AdaptiveByteStream.h
  src/Session.cpp
  src/Session.h
  src/SrvBroker.cpp
  src/SrvBroker.h
  src/Stream.h
  src/codechandler/AVCCodecHandler.cpp
  src/codechandler/AVCCodecHandler.h
  src/codechandler/CodecHandler.h
  src/common/AdaptationSet.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTreeFactory.cpp
  src/common/AdaptiveUtils.cpp
  src/common/Chooser.cpp
  src/common/Chooser.h
  src/common/ChooserAskQuality.cpp
  src/common/ChooserDefault.cpp
  src/common/ChooserFixedRes.cpp
  src/common/ChooserFixedRes.h
  src/common/ChooserManualOSD.cpp
  src/common/ChooserManualOSD.h
  src/common/ChooserTest.cpp
  src/common/CommonAttribs.cpp
  src/common/CommonAttribs.h
  src/common/Period.cpp
  src/common/Period.h
  src/common/ReprSelector.cpp
  src/common/ReprSelector.h
  src/main.cpp
  src/main.h
  src/parser/CodecParser.h
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/samplereader/ADTSSampleReader.cpp
  src/samplereader/ADTSSampleReader.h
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReaderFactory.cpp
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/samplereader/TSSampleReader.cpp
  src/samplereader/TSSampleReader.h
  src/samplereader/WebmSampleReader.cpp
  src/samplereader/WebmSampleReader.h
  src/test/TestDASHTree.cpp
  src/test/TestHelper.cpp
  src/test/TestHelper.h
  src/utils/Utils.h
Labels: Type: Cleanup, v21 Omega

#1414 Compile with multiprocessing for VS
  CMakeLists.txt
Labels: Platform: Windows, Component: Build, v21 Omega

#1416 [CSubtitleSampleReader] Initialize reader appropriately, add STPP fourcc
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  src/samplereader/SampleReaderFactory.cpp
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/samplereader/TSSampleReader.cpp
  src/samplereader/TSSampleReader.h
  src/samplereader/WebmSampleReader.cpp
  src/samplereader/WebmSampleReader.h
Labels: Type: Fix, v21 Omega

#1423 [Github/Workflow] Changed version / news default values
  .github/workflows/changelog-and-release.yml
Labels: v21 Omega

#1422 [DashTree] Implemented support to last segment number signal
  src/common/CommonSegAttribs.cpp
  src/common/CommonSegAttribs.h
  src/common/SegTemplate.cpp
  src/common/SegTemplate.h
  src/parser/DASHTree.cpp
Labels: Backport: Done, Type: Improvement, v21 Omega

#1425 [backport][DashTree] Implemented support to last segment number signal
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
Labels: v20 Nexus, Type: Improvement, Type: Partial backport
