Repository xbmc/inputstream.adaptive, pull requests merged in 2023-06, with the labels that each got.

#1270 [ADTS] add support for AC3 and E-AC3
  CMakeLists.txt
  depends/common/bento4/bento4.sha256
  depends/common/bento4/bento4.txt
  src/ADTSReader.cpp
  src/ADTSReader.h
  src/parser/CodecParser.cpp
  src/parser/CodecParser.h
Labels: Type: Feature, Component: Audio, v21 Omega

#1277 add missing cstdint include in test KodiStubs
  src/test/KodiStubs.h
Labels: Type: Fix, Component: Build, v21 Omega

#1253 [Session] Do not check GetInformation on GetNextSample
  src/Session.cpp
Labels: Type: Fix, v21 Omega

#1278 [HLSTree] Fix base url for relative uri key address
  src/parser/HLSTree.cpp
Labels: Type: Fix, Component: HLS, v21 Omega

#1267 [AdaptiveTree] Rework to autodetect manifest type
  CMakeLists.txt
  src/Session.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/common/AdaptiveTreeFactory.cpp
  src/common/AdaptiveTreeFactory.h
  src/main.cpp
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/parser/SmoothTree.cpp
  src/parser/SmoothTree.h
  src/test/CMakeLists.txt
  src/test/TestDASHTree.cpp
  src/test/TestHLSTree.cpp
  src/test/TestHelper.cpp
  src/test/TestHelper.h
  src/test/TestSmoothTree.cpp
  src/test/TestUtils.cpp
  src/test/manifests/hls/treefactory_test_regular.m3u8
  src/test/manifests/ism/treefactory_test_utf16leBOM.ism
  src/test/manifests/ism/treefactory_test_utf8.ism
  src/test/manifests/mpd/treefactory_test_regular.mpd
  src/utils/CurlUtils.cpp
  src/utils/CurlUtils.h
  src/utils/FileUtils.cpp
  src/utils/FileUtils.h
  src/utils/PropertiesUtils.cpp
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
Labels: Type: Feature, Type: Improvement, Wiki: Needed, v21 Omega

#1284 [DASHTree] Always set startNumber from SegmentTemplate
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/segmenttemplate_startnumber.mpd
Labels: Type: Fix, v21 Omega

#1286 [addon] Add Team Kodi to provider name
  inputstream.adaptive/addon.xml.in
Labels: v21 Omega

#1288 [AdaptiveTree] Rework of manifest update params
  inputstream.adaptive/addon.xml.in
  src/Session.cpp
  src/Session.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/SmoothTree.cpp
  src/test/TestDASHTree.cpp
  src/test/TestHelper.cpp
  src/test/TestHelper.h
  src/utils/PropertiesUtils.cpp
  src/utils/PropertiesUtils.h
Labels: Type: Breaking change, Type: Cleanup, Wiki: Needed, Component: MPEG-DASH, v21 Omega

#1293 [DASHTree] Dont force rounding segment count
  src/parser/DASHTree.cpp
  src/test/TestDASHTree.cpp
Labels: Type: Fix, Backport: Needed, v21 Omega

#1292 [AdaptiveTree] First rework to cleanup segment code
  CMakeLists.txt
  src/Session.cpp
  src/common/AdaptationSet.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveUtils.cpp
  src/common/AdaptiveUtils.h
  src/common/Representation.cpp
  src/common/Representation.h
  src/common/SegTemplate.cpp
  src/common/SegTemplate.h
  src/common/Segment.cpp
  src/common/Segment.h
  src/common/SegmentBase.cpp
  src/common/SegmentBase.h
  src/common/SegmentList.cpp
  src/common/SegmentList.h
  src/main.cpp
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/SmoothTree.cpp
  src/test/CMakeLists.txt
  src/test/TestDASHTree.cpp
Labels: Type: Cleanup, Type: Improvement, v21 Omega

#1300 [TSReader] Add code to debug TSDemux library
  src/TSReader.cpp
Labels: Type: Improvement, v21 Omega

#1301 Fixes for live streaming
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/parser/HLSTree.cpp
Labels: Type: Fix, Component: MPEG-DASH, Component: HLS, v21 Omega
