Repository xbmc/inputstream.adaptive, pull requests merged in 2023-08, with the labels that each got.

#1345 Small fix cleanups
  src/parser/HLSTree.cpp
  src/utils/StringUtils.cpp
Labels: Type: Fix, Type: Cleanup, v21 Omega

#1346 [wvdecrypter] Fix memory heap corruption
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: Type: Fix, Backport: Needed, v21 Omega

#1348 [backport] Removed extra memory reserved / fix memory heap corruption
  src/samplereader/FragmentedSampleReader.cpp
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1349 [HLSTree] Reworked multivariant playlist parser
  src/common/AdaptationSet.cpp
  src/common/AdaptationSet.h
  src/common/AdaptiveTree.cpp
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/parser/SmoothTree.cpp
  src/test/TestDASHTree.cpp
  src/test/TestHLSTree.cpp
  src/test/TestSmoothTree.cpp
  src/test/manifests/mpd/adaptation_set_merge.mpd
  src/test/manifests/mpd/adaptation_set_switching.mpd
  src/utils/Utils.cpp
  src/utils/Utils.h
Labels: Type: Fix, Type: Improvement, Component: HLS, v21 Omega

#1351 Some cleanup to AdaptiveStream and Session
  src/Session.cpp
  src/Session.h
  src/Stream.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/Chooser.h
  src/common/ChooserDefault.cpp
  src/common/ChooserDefault.h
  src/test/TestDASHTree.cpp
  src/test/TestHelper.h
Labels: Type: Cleanup, v21 Omega

#1353 [DASHTree] Limit insert live segs to uncovered interval cases
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
Labels: Type: Fix, v21 Omega

#1358 [AdaptiveStream] Fix sidx/init parsing
  src/Session.cpp
  src/Session.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/common/Representation.h
  src/main.cpp
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.h
  src/parser/SmoothTree.h
Labels: Type: Fix, v21 Omega

#1361 Add override identifier to InsertLiveSegment functions
  src/parser/DASHTree.h
  src/parser/SmoothTree.h
Labels: Type: Fix, v21 Omega

#1356 Implement set audio profile from demuxer
  lib/mpegts/ES_AAC.cpp
  lib/mpegts/ES_AAC.h
  lib/mpegts/elementaryStream.cpp
  lib/mpegts/elementaryStream.h
  src/ADTSReader.cpp
  src/ADTSReader.h
  src/Session.cpp
  src/TSReader.cpp
  src/codechandler/AudioCodecHandler.cpp
  src/codechandler/AudioCodecHandler.h
  src/codechandler/CodecHandler.cpp
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
  src/utils/Utils.h
Labels: Type: Improvement, v21 Omega
