Repository xbmc/inputstream.adaptive, pull requests merged in 2024-08, with the labels that each got.

#1609 [KodiProps] Deprecated license_url / license_url_append properties
  src/CompKodiProps.cpp
Labels: Type: Cleanup, Wiki: Needed, v22 Piers, Component: Properties

#1616 [AdaptiveTree] IsLastSegment return false if period is the last one
  src/common/AdaptiveTree.cpp
Labels: Type: Fix, Backport: Done, v22 Piers

#1621 [backport][AdaptiveTree] IsLastSegment return false if period is the last one
  src/common/AdaptiveTree.cpp
Labels: Type: Fix, Type: Backport, v21 Omega

#1618 [Deps] Reverted recents bento4 commits
  depends/common/bento4/bento4.sha256
  depends/common/bento4/bento4.txt
Labels: Type: Fix, Backport: Done, Component: Depends, v22 Piers

#1620 [backport][Deps] Reverted recents bento4 commits
  depends/common/bento4/bento4.sha256
  depends/common/bento4/bento4.txt
Labels: Type: Fix, Type: Backport, Component: Depends, v21 Omega

#1615 Fix wrong Dash KID data format and cleanups
  src/Session.cpp
  src/common/AdaptiveDecrypter.h
  src/decrypters/Helpers.cpp
  src/decrypters/Helpers.h
  src/decrypters/IDecrypter.h
  src/decrypters/clearkey/ClearKeyCencSingleSampleDecrypter.cpp
  src/decrypters/clearkey/ClearKeyCencSingleSampleDecrypter.h
  src/decrypters/clearkey/ClearKeyDecrypter.cpp
  src/decrypters/clearkey/ClearKeyDecrypter.h
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevine/WVCencSingleSampleDecrypter.h
  src/decrypters/widevine/WVDecrypter.cpp
  src/decrypters/widevine/WVDecrypter.h
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.h
  src/decrypters/widevineandroid/WVDecrypter.cpp
  src/decrypters/widevineandroid/WVDecrypter.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/PRProtectionParser.cpp
  src/parser/PRProtectionParser.h
  src/parser/SmoothTree.cpp
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/pssh_default_kid.mpd
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
  src/utils/Utils.cpp
  src/utils/Utils.h
Labels: Type: Fix, Backport: Done, Type: Cleanup, v22 Piers

#1622 [backport] Fix wrong Dash KID data format and cleanups
  src/Session.cpp
  src/common/AdaptiveDecrypter.h
  src/decrypters/Helpers.cpp
  src/decrypters/Helpers.h
  src/decrypters/IDecrypter.h
  src/decrypters/clearkey/ClearKeyCencSingleSampleDecrypter.cpp
  src/decrypters/clearkey/ClearKeyCencSingleSampleDecrypter.h
  src/decrypters/clearkey/ClearKeyDecrypter.cpp
  src/decrypters/clearkey/ClearKeyDecrypter.h
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevine/WVCencSingleSampleDecrypter.h
  src/decrypters/widevine/WVDecrypter.cpp
  src/decrypters/widevine/WVDecrypter.h
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.h
  src/decrypters/widevineandroid/WVDecrypter.cpp
  src/decrypters/widevineandroid/WVDecrypter.h
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/PRProtectionParser.cpp
  src/parser/PRProtectionParser.h
  src/parser/SmoothTree.cpp
  src/test/TestDASHTree.cpp
  src/test/manifests/mpd/pssh_default_kid.mpd
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
  src/utils/Utils.cpp
  src/utils/Utils.h
Labels: Type: Fix, Type: Backport, Type: Cleanup, v21 Omega

#1625 Fix build error with gcc 14
  src/decrypters/Helpers.h
Labels: Type: Fix, Backport: Done, v22 Piers

#1626 [Omega/backport] Fix build error with gcc 14
  src/decrypters/Helpers.h
Labels: Type: Fix, Type: Backport, v21 Omega

#1628 [Workflows][CI] Ubuntu build test with GCC14
  .github/workflows/build-ubuntu.yml
Labels: Component: Build

#1630 [ADTSReader] Return false when id3tagparser fails due to eos
  src/demuxers/ADTSReader.cpp
Labels: Type: Fix, Backport: Done, v22 Piers

#1631 [backport][ADTSReader] Return false when id3tagparser fails due to eos
  src/demuxers/ADTSReader.cpp
Labels: Type: Fix, Type: Backport, v21 Omega

#1633 [Session] Restored licenseData variable on for loop
  src/Session.cpp
Labels: Type: Fix, Backport: Done, v22 Piers

#1634 [Session] Restored licenseData variable on for loop
  src/Session.cpp
Labels: Type: Fix, Type: Backport, v21 Omega

#1639 [Session] Reworked widevine pssh generation for smoothstreaming
  src/Session.cpp
  src/decrypters/Helpers.cpp
  src/decrypters/Helpers.h
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVDecrypter.h
Labels: Type: Fix, Backport: Needed, Type: Cleanup, Wiki: Done, DRM: Widevine, Component: SmoothStream, v22 Piers

#1638 [DRM][ClearKey] Add license url by DRM config, CK as DRM replacement
  src/CompKodiProps.cpp
  src/CompKodiProps.h
  src/Session.cpp
  src/decrypters/clearkey/ClearKeyCencSingleSampleDecrypter.cpp
  src/decrypters/clearkey/ClearKeyCencSingleSampleDecrypter.h
  src/decrypters/clearkey/ClearKeyDecrypter.cpp
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/utils/Base64Utils.cpp
  src/utils/Base64Utils.h
  src/utils/CurlUtils.cpp
  src/utils/CurlUtils.h
  src/utils/StringUtils.h
Labels: Backport: Done, Type: Improvement, Wiki: Done, v22 Piers, DRM: ClearKey

#1641 [backport][DRM][ClearKey] Add license url by DRM config, CK as DRM replacement
  src/CompKodiProps.cpp
  src/CompKodiProps.h
  src/Session.cpp
  src/decrypters/clearkey/ClearKeyCencSingleSampleDecrypter.cpp
  src/decrypters/clearkey/ClearKeyCencSingleSampleDecrypter.h
  src/decrypters/clearkey/ClearKeyDecrypter.cpp
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/utils/Base64Utils.cpp
  src/utils/Base64Utils.h
  src/utils/CurlUtils.cpp
  src/utils/CurlUtils.h
  src/utils/StringUtils.h
Labels: Type: Backport, Type: Improvement, v21 Omega, DRM: ClearKey

#1647 [AdaptiveUtils] Fix defaultkid to tenc atom on CreateMovieAtom
  src/common/AdaptiveUtils.cpp
Labels: Type: Fix, Backport: Done, v22 Piers

#1648 [backport][AdaptiveUtils] Fix defaultkid to tenc atom on CreateMovieAtom
  src/common/AdaptiveUtils.cpp
Labels: Type: Fix, Type: Backport, v21 Omega

#1643 [HLS] Implemented PlayReady support
  src/common/AdaptiveUtils.h
  src/parser/HLSTree.cpp
  src/parser/PRProtectionParser.cpp
  src/parser/PRProtectionParser.h
Labels: Type: Fix, Type: Feature, Wiki: Done, DRM: PlayReady, Component: HLS, v22 Piers

#1651 [PRProtectionParser] Fix KID parsing
  src/parser/PRProtectionParser.cpp
Labels: Type: Fix, Type: Partial backport, v21 Omega

#1649 [DashTree] Improved clearkey defaultkid workaround
  src/Session.cpp
  src/Session.h
  src/main.cpp
  src/parser/DASHTree.cpp
Labels: Backport: Done, Type: Improvement, v22 Piers, DRM: ClearKey

#1650 [backport][DashTree] Improved clearkey defaultkid workaround
  src/Session.cpp
  src/Session.h
  src/main.cpp
  src/parser/DASHTree.cpp
Labels: Type: Backport, Type: Improvement, v21 Omega, DRM: ClearKey

#1652 [Decrypters] Introduction of protection_scheme to Widevine PSSH
  src/decrypters/Helpers.cpp
Labels: Type: Cleanup, DRM: Widevine, v22 Piers

#1653 [Session][CDM] Dont initialize already initialized sessions
  src/Session.cpp
Labels: Type: Fix, Backport: Needed, v22 Piers

#1655 [ClearKey] Fix base64 encoding/decoding
  src/decrypters/clearkey/ClearKeyCencSingleSampleDecrypter.cpp
  src/utils/Base64Utils.cpp
  src/utils/Base64Utils.h
Labels: Type: Fix, Backport: Done, v22 Piers, DRM: ClearKey

#1658 [backport][ClearKey] Fix base64 encoding/decoding
  src/decrypters/clearkey/ClearKeyCencSingleSampleDecrypter.cpp
  src/utils/Base64Utils.cpp
  src/utils/Base64Utils.h
Labels: Type: Fix, Type: Backport, v21 Omega, DRM: ClearKey

#1662 [Session] Fix wrong KID conversion
  src/Session.cpp
Labels: Type: Fix, Backport: Done, v22 Piers

#1663 [Session] Fix wrong KID conversion
  src/Session.cpp
Labels: Type: Fix, Type: Backport, v21 Omega

#1661 [AdaptiveTree] Fix spurious wakeups on TreeUpdateThread
  src/common/AdaptiveTree.cpp
Labels: Type: Fix, Backport: Done, v22 Piers

#1665 [backport][AdaptiveTree] Fix spurious wakeups on TreeUpdateThread
  src/common/AdaptiveTree.cpp
Labels: Type: Fix, Type: Backport, v21 Omega

#1666 [backport][Session] Reworked widevine pssh generation for smoothstreaming
  src/Session.cpp
  src/decrypters/Helpers.cpp
  src/decrypters/Helpers.h
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVDecrypter.h
Labels: Type: Fix, Type: Backport, Type: Cleanup, DRM: Widevine, Component: SmoothStream, v21 Omega

#1667 [backport][Session][CDM] Dont initialize already initialized sessions
  src/Session.cpp
Labels: Type: Fix, Type: Backport, v21 Omega

#1668 Cleanups / Improvements to PSSH, KID, init data
  src/Session.cpp
  src/Session.h
  src/decrypters/CMakeLists.txt
  src/decrypters/HelperPr.cpp
  src/decrypters/HelperPr.h
  src/decrypters/HelperWv.cpp
  src/decrypters/HelperWv.h
  src/decrypters/Helpers.cpp
  src/decrypters/Helpers.h
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.cpp
  src/parser/CMakeLists.txt
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/PRProtectionParser.cpp
  src/parser/PRProtectionParser.h
  src/parser/SmoothTree.cpp
  src/parser/SmoothTree.h
  src/test/CMakeLists.txt
  src/utils/CharArrayParser.cpp
  src/utils/CharArrayParser.h
Labels: Type: Cleanup, Type: Improvement, v22 Piers
