Repository xbmc/inputstream.adaptive, pull requests merged in 2024-05, with the labels that each got.

#1543 Removed outdated todo
  src/main.cpp
Labels: Type: Cleanup, v21 Omega

#1542 [Widevine] Fix CreateDirs
  lib/cdm/cdm/media/cdm/cdm_adapter.cc
Labels: Type: Fix, DRM: Widevine, v21 Omega

#1532 [HLSTree] New hls_ignore_endlist, hls_fix_mediasequence, hls_fix_discsequence params to fix faulty live services
  src/CompKodiProps.cpp
  src/CompKodiProps.h
  src/Session.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/common/Period.cpp
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/test/TestHLSTree.cpp
Labels: Type: Improvement, Wiki: Done, v21 Omega

#1547 [HLSTree] Fix and cleanup to encryption types/states
  src/Session.cpp
  src/common/AdaptationSet.cpp
  src/common/AdaptiveUtils.h
  src/common/Period.cpp
  src/common/Representation.cpp
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/SmoothTree.cpp
  src/test/TestHLSTree.cpp
  src/test/TestHelper.h
  src/test/manifests/hls/encrypt_master.m3u8
  src/test/manifests/hls/encrypt_master_drm.m3u8
  src/test/manifests/hls/encrypt_seq_stream.m3u8
  src/test/manifests/hls/encrypt_seq_stream_drm.m3u8
Labels: Type: Fix, Type: Cleanup, v21 Omega

#1552 [XMLUtils] Fix wrong result of ParseData due to second fraction
  src/test/TestUtils.cpp
  src/utils/XMLUtils.cpp
Labels: Type: Fix, v21 Omega

#1554 [CurlUtils] Fix internal cookies expiration check
  src/utils/CurlUtils.cpp
Labels: Type: Fix, v21 Omega

#1555 [AdaptiveStream] Find segment by number otherwise by pts
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/Representation.h
  src/common/SegTemplate.cpp
  src/common/SegTemplate.h
  src/common/Segment.h
  src/parser/DASHTree.cpp
Labels: Type: Fix, Component: HLS, v21 Omega

#1559 [Omega] Use dca for dts codec name (regression fix)
  src/utils/Utils.h
Labels: Type: Fix, v21 Omega

#1556 [HLSTree] Moved back insert psshset to EXTINF parsing
  src/parser/HLSTree.cpp
Labels: Type: Fix, Component: HLS, v21 Omega

#1562 AdaptiveTree methods cleanups and fix period change for HLS case
  src/Session.cpp
  src/Session.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.cpp
  src/common/AdaptiveTree.h
  src/common/Representation.h
  src/main.cpp
  src/main.h
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/test/TestHLSTree.cpp
  src/test/TestHelper.cpp
Labels: Type: Fix, Type: Cleanup, Component: HLS, v21 Omega

#1564 [Github] New YAML bug report and feature request
  .github/ISSUE_TEMPLATE/01_bug_report.yml
  .github/ISSUE_TEMPLATE/02_feature_request.yml
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Documentation
