Repository xbmc/inputstream.adaptive, pull requests merged in 2024-11, with the labels that each got.

#1716 [backport][HLS] Fix misaligned periods update for VOD and crash
  src/Session.cpp
  src/Session.h
  src/main.cpp
  src/parser/HLSTree.cpp
Labels: Type: Fix, Type: Backport, v21 Omega

#1710 [FragmentedSampleReader] Check default_isProtected before add senc
  src/common/AdaptiveUtils.cpp
  src/samplereader/FragmentedSampleReader.cpp
Labels: Type: Fix, v22 Piers

#1718 [SampleReader][cleanups] Separate Get/Set stream id methods
  src/main.cpp
  src/main.h
  src/samplereader/ADTSSampleReader.cpp
  src/samplereader/ADTSSampleReader.h
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  src/samplereader/SampleReaderFactory.cpp
  src/samplereader/SampleReaderFactory.h
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/samplereader/TSSampleReader.cpp
  src/samplereader/TSSampleReader.h
  src/samplereader/WebmSampleReader.cpp
  src/samplereader/WebmSampleReader.h
Labels: Type: Cleanup, v22 Piers

#1720 Moved extradata conversions to more appropriate places
  src/Session.cpp
  src/codechandler/AVCCodecHandler.cpp
  src/codechandler/AVCCodecHandler.h
  src/codechandler/CodecHandler.h
  src/codechandler/HEVCCodecHandler.cpp
  src/codechandler/HEVCCodecHandler.h
  src/common/AdaptiveUtils.cpp
  src/parser/DASHTree.cpp
  src/parser/SmoothTree.cpp
  src/samplereader/FragmentedSampleReader.cpp
  src/utils/StringUtils.cpp
  src/utils/StringUtils.h
  src/utils/Utils.cpp
  src/utils/Utils.h
Labels: Type: Cleanup, v22 Piers

#1722 [FragmentedSampleReader] restore codechandler GetInformation
  src/samplereader/FragmentedSampleReader.cpp
Labels: Type: Fix, v22 Piers

#1725 [Omega] Extract default kid from init data if required
  src/Session.cpp
Labels: Type: Fix, Type: Partial backport, v21 Omega

#1728 [codechandler] Removed ExtraDataToAnnexB and cleanups
  src/codechandler/AVCCodecHandler.cpp
  src/codechandler/AVCCodecHandler.h
  src/codechandler/CodecHandler.h
  src/codechandler/HEVCCodecHandler.cpp
  src/codechandler/HEVCCodecHandler.h
  src/samplereader/FragmentedSampleReader.cpp
  src/utils/Utils.cpp
  src/utils/Utils.h
Labels: Type: Improvement, v22 Piers

#1729 Fix widevine on aarch64
  lib/cdm_aarch64/cdm_loader.cpp
Labels: Type: Fix, DRM: Widevine, v22 Piers

#1731 [AdaptiveTree] On parsers use "und" language code for unknown cases
  src/Session.cpp
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/SmoothTree.cpp
  src/utils/Utils.h
Labels: Type: Cleanup, v22 Piers

#1733 [HLSTree] Add support to read subtitle codec
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
Labels: Type: Improvement, Component: Subtitles, Component: HLS, v22 Piers
