Repository xbmc/inputstream.adaptive, pull requests merged in 2024-01, with the labels that each got.

#1445 [backport][HLSTree] Fix container m4s, fix avc codec detection
  src/parser/HLSTree.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1451 add support for loongarch
  wvdecrypter/cdm/build/build_config.h
Labels: v20 Nexus, Type: Backport, Type: Improvement, Component: Build

#1449 Some tree / session cleanups
  src/Session.cpp
  src/Session.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.h
  src/common/ChooserAskQuality.cpp
  src/main.cpp
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
Labels: Type: Fix, Type: Cleanup, v21 Omega

#1454 [WebVTT] Reverted changes to align stream and fix turn off/on subs
  src/Session.cpp
  src/Session.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveUtils.h
  src/demuxers/TSReader.cpp
  src/demuxers/TSReader.h
  src/main.cpp
  src/main.h
  src/samplereader/ADTSSampleReader.h
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/samplereader/TSSampleReader.cpp
  src/samplereader/TSSampleReader.h
  src/samplereader/WebmSampleReader.h
Labels: Type: Fix, Component: Subtitles, v21 Omega

#1455 [Widevine] Accept R for raw response data
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.cpp
Labels: Type: Fix, Backport: Done, v21 Omega

#1456 [backport][Widevine] Accept R for raw response data
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1459 [AdaptiveStream] Rework to improve HLS manifest updates
  src/Session.cpp
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.h
  src/common/AdaptiveUtils.h
  src/common/Representation.cpp
  src/common/Representation.h
  src/main.cpp
  src/parser/DASHTree.cpp
  src/parser/HLSTree.cpp
  src/parser/HLSTree.h
  src/samplereader/SampleReader.h
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/test/TestHLSTree.cpp
Labels: Type: Fix, Type: Cleanup, v21 Omega

#1457 [backport][WebVTT] Reverted changes to align stream and fix turn off/on subs
  src/Session.cpp
  src/Session.h
  src/TSReader.cpp
  src/TSReader.h
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveStream.h
  src/common/AdaptiveTree.h
  src/main.cpp
  src/main.h
  src/samplereader/ADTSSampleReader.h
  src/samplereader/FragmentedSampleReader.cpp
  src/samplereader/FragmentedSampleReader.h
  src/samplereader/SampleReader.h
  src/samplereader/SubtitleSampleReader.cpp
  src/samplereader/SubtitleSampleReader.h
  src/samplereader/TSSampleReader.cpp
  src/samplereader/TSSampleReader.h
  src/samplereader/WebmSampleReader.h
Labels: Type: Fix, v20 Nexus, Type: Backport, Component: Subtitles

#1463 [backport][UrlUtils]: Append parameters to an URL without overwriting existing...
  src/common/AdaptiveStream.cpp
  src/common/AdaptiveTree.cpp
  src/samplereader/SubtitleSampleReader.cpp
  src/utils/UrlUtils.cpp
  src/utils/UrlUtils.h
Labels: v20 Nexus, Type: Backport, Type: Improvement
