Repository xbmc/inputstream.adaptive, pull requests merged in 2024-02, with the labels that each got.

#1462 [ChooserManualOSD] Fix wrong resolution
  src/Session.cpp
  src/common/Chooser.h
  src/common/ChooserManualOSD.cpp
  src/common/ChooserManualOSD.h
Labels: Type: Fix, v21 Omega

#1464 [widevine] Fix bad data pointer on clrb_out variable
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.cpp
Labels: Type: Fix, Backport: Done, DRM: Widevine, v21 Omega

#1467 [backport][widevine] Fix bad data pointer on clrb_out variable
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport, DRM: Widevine

#1470 [UrlUtils] Fix substr on AppendParameters and restored add params to manifest url
  src/Session.cpp
  src/utils/UrlUtils.cpp
Labels: Type: Fix, Backport: Done, v21 Omega

#1471 [backport][UrlUtils] Fix substr on AppendParameters
  src/utils/UrlUtils.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport

#1472 [github] Updated deprecated workflows actions
  .github/workflows/build.yml
  .github/workflows/changelog-and-release.yml
  .github/workflows/increment-version.yml
  .github/workflows/release.yml
Labels: Backport: Needed, Component: Build, v21 Omega

#1477 [backport][github] Updated deprecated workflows actions
  .github/workflows/build.yml
  .github/workflows/changelog-and-release.yml
  .github/workflows/increment-version.yml
  .github/workflows/release.yml
Labels: v20 Nexus, Type: Backport, Component: Build

#1475 [Widevine] Fix wrong byte position of clearbytes data array
  src/decrypters/widevine/WVCencSingleSampleDecrypter.cpp
  src/decrypters/widevineandroid/WVCencSingleSampleDecrypter.cpp
Labels: Type: Fix, Backport: Done, DRM: Widevine, v21 Omega

#1476 [backport][Widevine] Fix wrong byte position of clearbytes data array
  wvdecrypter/wvdecrypter.cpp
  wvdecrypter/wvdecrypter_android.cpp
Labels: Type: Fix, v20 Nexus, Type: Backport, DRM: Widevine

#1478 [Dash] Removed segment limit based on SIDX refs
  src/parser/DASHTree.cpp
Labels: Type: Fix, Component: MPEG-DASH, v21 Omega

#1479 [DashTree] Skip encrypted subtitle streams
  src/parser/DASHTree.cpp
Labels: Type: Improvement, Component: Subtitles, Component: MPEG-DASH, v21 Omega

#1482 [widevine] Use mac library filename for all darwin platforms
  src/decrypters/widevine/WVCdmAdapter.cpp
Labels: Type: Fix, DRM: Widevine, v21 Omega

#1485 [workflows] Fix multiline for changes var
  .github/workflows/changelog-and-release.yml
Labels: Type: Fix, v21 Omega

#1486 [workflows] Try fix Invalid format error
  .github/workflows/changelog-and-release.yml
Labels: Type: Fix, v21 Omega

#1487 Use a random EOF (best practice) for multiline changes variable and update label to Omega
  .github/workflows/changelog-and-release.yml
  .github/workflows/release.yml
Labels: v21 Omega

#1488 [backport][workflows] Removed char replaces on changelog and release actions
  .github/workflows/changelog-and-release.yml
  .github/workflows/release.yml
Labels: Type: Fix, v20 Nexus

#1489 [DashTree] Fix setting default AdaptationSet using ISA specific default attribute
  src/parser/DASHTree.cpp
Labels: Type: Fix, Component: MPEG-DASH, v21 Omega

#1490 Fix github workflows
  .github/workflows/changelog-and-release.yml
  .github/workflows/increment-version.yml
Labels: Type: Fix, v21 Omega

#1483 [DashTree] Cleanups and fixes
  src/common/AdaptationSet.cpp
  src/common/AdaptationSet.h
  src/common/AdaptiveTree.h
  src/common/CommonSegAttribs.cpp
  src/common/CommonSegAttribs.h
  src/common/Period.h
  src/common/Representation.cpp
  src/common/Representation.h
  src/common/SegTemplate.cpp
  src/common/SegTemplate.h
  src/common/Segment.h
  src/common/SegmentList.cpp
  src/common/SegmentList.h
  src/parser/DASHTree.cpp
  src/parser/DASHTree.h
Labels: Type: Fix, Type: Cleanup, Component: MPEG-DASH, v21 Omega
