Repository xbmc/inputstream.adaptive, pull requests merged in 2025-03, with the labels that each got.

#1786 [azure] Disabled unmaintained ARM32-UWP, updated sdk
  azure-pipelines.yml
  lib/cdm/cdm/build/build_config.h
  src/common/AdaptiveStream.h
Labels: Type: Fix, Component: Build, v22 Piers

#1787 Updated dependencies and CMake 4.0 fixes
  depends/common/googletest/CMakeLists.txt
  depends/common/googletest/googletest.sha256
  depends/common/googletest/googletest.txt
  depends/common/pugixml/pugixml.sha256
  depends/common/pugixml/pugixml.txt
  depends/common/rapidjson/rapidjson.sha256
  depends/common/rapidjson/rapidjson.txt
  depends/windows/dlfcn-win32/0001-dlopen_with_widechar.patch
  depends/windows/dlfcn-win32/dlfcn-win32.sha256
  depends/windows/dlfcn-win32/dlfcn-win32.txt
  depends/windowsstore/dlfcn-win32/0001-win10-fixed-uwp-build.patch
  depends/windowsstore/dlfcn-win32/dlfcn-win32.sha256
  depends/windowsstore/dlfcn-win32/dlfcn-win32.txt
  src/test/TestDASHTree.cpp
  src/test/TestHelper.h
Labels: Type: Fix, Type: Improvement, Component: Build, v22 Piers

#1785 [SrvBroker] Init/Deinit data to avoid resilient stored data
  src/CompKodiProps.cpp
  src/CompKodiProps.h
  src/SrvBroker.cpp
  src/SrvBroker.h
  src/main.cpp
  src/test/TestDASHTree.cpp
  src/test/TestHLSTree.cpp
  src/test/TestSmoothTree.cpp
  src/utils/ThreadPool.cpp
  src/utils/ThreadPool.h
Labels: Type: Fix, v22 Piers

#1790 [FragmentedSampleReader] Fix transitions from unencrypted fragments to encrypted
  src/samplereader/FragmentedSampleReader.cpp
Labels: Type: Fix, Backport: Done, v22 Piers

#1791 [Backport] [FragmentedSampleReader] Fix transitions from unencrypted fragments to encrypted
  src/samplereader/FragmentedSampleReader.cpp
Labels: Type: Fix, Type: Backport, v21 Omega

#1792 [backport][azure] Disabled unmaintained ARM32-UWP
  azure-pipelines.yml
  src/common/AdaptiveStream.h
Labels: Type: Fix, Type: Partial backport, Component: Build, v21 Omega

#1793 [HLSTree] Set period duration also with live stream
  src/parser/HLSTree.cpp
Labels: Type: Fix, Backport: Done, Component: HLS, v22 Piers

#1796 [HLSTree] Fix media sequence number on discontinuity
  plugin.video.isasamples/menu_data.py
  src/parser/HLSTree.cpp
Labels: Type: Fix, Backport: Done, Component: HLS, v22 Piers

#1797 [backport][HLSTree] Fix media sequence number on discontinuity
  src/parser/HLSTree.cpp
Labels: Type: Fix, Type: Backport, Component: HLS, v21 Omega

#1798 [UrlUtils] Fix GetBaseDomain for SMIL URLs
  src/test/TestUtils.cpp
  src/utils/UrlUtils.cpp
Labels: Type: Fix, Backport: Done, v22 Piers

#1799 [backport][UrlUtils] Fix GetBaseDomain for SMIL URLs
  src/test/TestUtils.cpp
  src/utils/UrlUtils.cpp
Labels: Type: Fix, Type: Backport, v21 Omega
